config/routes.rb
Interpolator::Application.routes.draw do
  

  match '/rate' => 'rater#create', :as => 'rate'

  resources :interpolations do
    member do
      post 'rate' 
    end
    resources :comments
    resources :downloads
  end

  resources :users

  resources :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'interpolations#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :interpolation_id, :user_id
  belongs_to :interpolation, :counter_cache => true
  belongs_to :user
  attr_accessible :content
  validates_presence_of :content
  validates_associated :interpolation, :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @interpolation = Interpolation.find(params[:interpolation_id])
    @comments = @interpolation.comments
  end
  
  def new
    if !current_user
      flash[:notice] = "You must sign in or register to do this."
      redirect_to new_user_path
    else
      respond_to do |format|
        format.html { @interpolation = Interpolation.find(params[:interpolation_id])
          @comment = @interpolation.comments.build }
        format.js {}
    end
   end
  end
  
  def create
    @interpolation = Interpolation.find(params[:interpolation_id])
    @comment = @interpolation.comments.build(params[:comment])
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html {redirect_to interpolation_url(@comment.interpolation_id), notice: "Successfully created comment."}
        format.js {}
      else
        format.html{render :action => 'new'}
      end
    end
  end
  
  
  def destroy
    @comment = Comment.find(params[:id])
    if current_user != @comment.user
      flash[:notice] = "You can't delete this comment."
    else
      @comment.destroy
      flash[:notice] = "Successfully destroyed comment."
      redirect_to interpolation_url(@comment.interpolation_id)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div id="login2">
<%= form_for([@interpolation, @comment]) do |f| %>
<% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :content %>
  <%= f.submit :id => 'submit' %>
  <% end %>
</div>

app/views/comments/_show.html.erb
<b><%=comment.user.username%></b>
    
    <p><%= comment.content%></p>
    <p><%= comment.created_at%></p>

app/views/comments/index.html.erb
<h1>Comments</h1>
<% @comments.each do |comment| %>
<p><b><%= comment.user.username %></b></p>
<p><%= comment.content %></p>
<% end %>

<br />

<%= link_to 'Add Comment', new_interpolation_comment_path(@interpolation) %>

app/views/comments/new.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %>
<h1 class="centerer">New Comment</h1>

<%= render 'form' %>


<p id="backlink"><%= link_to 'Back', interpolation_path(@interpolation) %></p>

app/views/comments/new.js.erb
$('#comments').append("<%= escape_javascript(render :partial => '/comments/form', :interpolation => @interpolation, :comment => @interpolation.comments.build)%>");