config/routes.rb
Interpolator::Application.routes.draw do
  

  match '/rate' => 'rater#create', :as => 'rate'

  resources :interpolations do
    member do
      post 'rate' 
    end
    resources :comments
    resources :downloads
  end

  resources :users

  resources :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'interpolations#index'

end

app/models/interpolation.rb
class Interpolation < ActiveRecord::Base
   
  attr_accessible :name, :private, :changes_attributes, :rating_average
  scope :public, where(private: false)
  scope :private, where(private: true)
  belongs_to :user
  has_many :changes
  has_many :downloads
  has_many :comments
  has_many :ratings
  validates_associated :user
  accepts_nested_attributes_for :changes

  ajaxful_rateable :stars => 5, :allow_update => true, :dimsensions => [:awesomeness]
  letsrate_rateable

  def self.most_recent
    order("created_at desc")
  end

  def self.most_downloaded
    order("downloads_count desc")
  end

  def self.highest_rated
    order("rating_average desc")
  end

  def self.avereage_rating

  end

  def self.today
    where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def self.this_week
    where("created_at >= ?", Time.zone.now.beginning_of_week)
  end

  def self.this_month
    where("created_at >= ?", Time.zone.now.beginning_of_month)
  end

  def self.this_year
    where("created_at >= ?", Time.zone.now.beginning_of_year)
  end
end

app/controllers/interpolations_controller.rb
class InterpolationsController < ApplicationController
  # GET /interpolations
  # GET /interpolations.json
  def index
    @interpolations = Interpolation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interpolations }
    end
  end

  # GET /interpolations/1
  # GET /interpolations/1.json
  def show
    @interpolation = Interpolation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interpolation }
    end
  end

  # GET /interpolations/new
  # GET /interpolations/new.json
  def new
    if !current_user
      flash[:notice] = "You must sign in or register to do this."
      redirect_to new_user_path
    else
    @interpolation = Interpolation.new
    @interpolation.changes.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interpolation }
    end
  end
  end

  # GET /interpolations/1/edit
  def edit
    @interpolation = Interpolation.find(params[:id])
    if current_user != @interpolation.user
      flash[:notice] = "You can't edit this."
      redirect_to interpolation_path(@interpolation)
    end
  end

  # POST /interpolations
  # POST /interpolations.json
  def create
    @interpolation = Interpolation.new(params[:interpolation])

    @interpolation.user_id = current_user.id

    respond_to do |format|
      if @interpolation.save
        format.html { redirect_to @interpolation, notice: 'Interpolation was successfully created.' }
        format.json { render json: @interpolation, status: :created, location: @interpolation }
      else
        format.html { render action: "new" }
        format.json { render json: @interpolation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interpolations/1
  # PUT /interpolations/1.json
  def update
    @interpolation = Interpolation.find(params[:id])

    respond_to do |format|
      if @interpolation.update_attributes(params[:interpolation])
        format.html { redirect_to @interpolation, notice: 'Interpolation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interpolation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interpolations/1
  # DELETE /interpolations/1.json
  def destroy
    @interpolation = Interpolation.find(params[:id])
    if current_user != @interpolation.user
      flash[:notice] = "You can't do this."
      redirect_to interpolation_path(@interpolation)
    end
    @interpolation.destroy

    respond_to do |format|
      format.html { redirect_to interpolations_url }
      format.json { head :no_content }
    end
  end

  def rate
    @interpolation = Interpolation.find(params[:id])
    @interpolation.rate(params[:stars], current_user, params[:dimension])
    render :update do |page|
      page.replace_html @interpolation.wrapper_dom_id(params), ratings_for(@interpolation, params.merge(:wrap => false))
      page.visual_effect :highlight, @interpolation.wrapper_dom_id(params)
    end
  end
end

app/helpers/interpolations_helper.rb
module InterpolationsHelper
end

app/views/interpolations/_change_fields.html.erb
<div class="field">
      <%= f.label :regex_old %><br />
      
      <%= f.text_field :regex_old %><br />
    
      <%= f.label :regex_new %><br />
      <%= f.text_field :regex_new %><%= link_to_remove_fields "remove", f %><br />
    </div>

app/views/interpolations/_comment.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.label :content %><br />
  <%= f.text_area :content %><br />
  <%= f.submit %>
  <%end%>

app/views/interpolations/_form.html.erb
<%= form_for(@interpolation) do |f| %>
  <% if @interpolation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interpolation.errors.count, "error") %> prohibited this interpolation from being saved:</h2>

      <ul>
      <% @interpolation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="login2">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div>
  <%= f.fields_for :changes do |c| %>
    <%= render "change_fields", :f => c %>
  <%end%>

  <%= link_to_add_fields "Add Change", f, :changes %>
</div>
  <div class="actions">
    <%= f.submit :id => 'submit'%>
  </div>
</div>
<% end %>

app/views/interpolations/edit.html.erb
<%= image_tag("logo_int.gif", :alt => "Interpolator") %>
<h1 class="centerer">Editing interpolation</h1>

<%= render 'form' %>

<p id="backlink"><%= link_to 'Show', @interpolation %> |
<%= link_to 'Back', interpolations_path %>
</p>

app/views/interpolations/index.html.erb
<script>
	$(document).ready(function() {
		$("#sync").click(function() {
			console.log(this.value);
		});
	});
</script>
        <div id="logo">
        	<%= image_tag("logo_int.gif", :alt => "Interpolator") %>
        </div>
	<div id="sidebox">
		<!-- <div id="login">
                	<h3>Login:</h3>
			<form>
				Username:<input type="text" name="username" id="username"/>
				<br />
				Password:<input type="password" name="password" />
				<br />
				<a href="signup.html">SIGN UP</a>
				<input type="submit" value="Login!" name="login" id="submit"/>
			
			</form>
		</div> -->
		<p id="notice"><%= notice %></p>
		<div id="new">
			<h3>Make a new Interpolator:</h3>
			<%= button_to 'New Interpolation', new_interpolation_path, :method=> :get, :id=> "new_int" %>
			<% if current_user %>
			<button id="sync" value= '<%= current_user.options %>'>SYNC</button>
			<%end%>
        </div>
	</div>
	<div id="big_main">
		<% if current_user %>	
		<div id="right_side">
			<h3> Your Interpolations:</h3>
			<ul>
			<% current_user.interpolations.each do |i| %>
				<li><%= link_to i.name, i %></li>
			<% end %>
			</ul>	
		</div>
		<% else %>
		<% end %>
        <div id="main" ">
		<div id="tabs">
			<ul>
				<li><a href="#tabs-1">BEST</a></li>
				<li><a href="#tabs-2">NEWEST</a></li>
				<li><a href="#tabs-3">MOST DOWNLOADED</a></li>
			</ul>
			<div id="tabs-1">
				<% Interpolation.highest_rated.each do |i| %>
				<div class="interpolator">
                 	<h3 id="int_namer"><%= i.name %></h3>
                 	<div id="upline">
           			<b>Average Rating: </b>
           			<%= i.rating_average %>
           			<b>Downloads: </b>
           			<%= i.downloads_count %>
           			</div>
                 	<br /> 
                 	<p>Created by:<%= link_to i.user.username, i.user %> </p>
           			<br />
                 	<div id="inner">
                 	<%= link_to 'Show', i %>
                 	<% if current_user == i.user %>
                 	<%= link_to 'Edit', edit_interpolation_path(i) %>
                 	<%= link_to 'Destroy', i, method: :delete, data: { confirm: 'Are you sure you want to deleter your Interpolation?' } %>
                 	<% end %>
                 	</div>
                </div>
                <% end %>
                		
			</div>
			<div id="tabs-2">
				<% Interpolation.most_recent.each do |i| %>
				<div class="interpolator">
                 	<h3 id="int_namer"><%= i.name %></h3>
                 	<div id="upline">
                 	<b>Average Rating: </b>
           			<%= i.rating_average %>
           			<b>Downloads: </b>
           			<%= i.downloads_count %>
           			</div>
                 	<br /> 
                 	<p>Created by:<%= link_to i.user.username, i.user %> </p>
           			<br />
                 	<div id="inner">
                 	<%= link_to 'Show', i %>
                 	<% if current_user == i.user %>
                 	<%= link_to 'Edit', edit_interpolation_path(i) %>
                 	<%= link_to 'Destroy', i, method: :delete, data: { confirm: 'Are you sure you want to deleter your Interpolation?' } %>
                 	<% end %>
                 	</div>
                </div>
                <% end %>   
			</div>
			<div id="tabs-3">
				<% Interpolation.most_downloaded.each do |i| %>
				<div class="interpolator">
                 	<h3 id="int_namer"><%= i.name %></h3>
                 	<div id="upline">
           			<b>Average Rating: </b>
           			<%= i.rating_average %>
           			<b>Downloads: </b>
           			<%= i.downloads_count %>
           			</div>
                 	<br /> 
                 	<p>Created by:<%= link_to i.user.username, i.user %> </p>
           			<br />
                 	<div id="inner">
                 	<%= link_to 'Show', i %>
                 	<% if current_user == i.user %>
                 	<%= link_to 'Edit', edit_interpolation_path(i) %>
                 	<%= link_to 'Destroy', i, method: :delete, data: { confirm: 'Are you sure you want to deleter your Interpolation?' } %>
                 	<% end %>
                 	</div>
                </div>
                <% end %>
			</div> 
	        </div>
        </div>
        </div>

app/views/interpolations/new.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %>
<h1 class="centerer">New interpolation</h1>

<%= render 'form' %>


<p id="backlink"><%= link_to 'Back', interpolations_path %></p>

app/views/interpolations/show.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %>
<p id="notice"><%= notice %></p>
<div id="page">
<h1>
  <%= @interpolation.name %>
</h1>

<p>
  <b>Created by:</b>
  <%=link_to @interpolation.user.username, @interpolation.user %>
</p>
<div id="explanation" >
<% @interpolation.changes.each do |change| %>
  <dl>
    <dt><b>Change: </b></dt>    
    <dd><%= change.regex_old%></dd>
    <dt><b>To: </b></dt>
    <dd><%= change.regex_new%></dd>
  </dl>
<% end %>
</div>
<hr />
<h2><b>Comments:</b></h2>

<% @interpolation.comments.each do |comment| %>
  <div id="comment">
  <p>
    <b><%=comment.user.username%></b>
    
    <p><%= comment.content%></p>
    <p id="timestamp"><%= comment.created_at%></p>
  </p>
  </div>
<% end %>

<div id="comments">

<%= link_to 'Add comment', new_interpolation_comment_path(@interpolation) %>
</div>
<%= ratings_for @interpolation, :dimensions => :awesomeness %>
<p>
  <b><%= pluralize(@interpolation.downloads_count, "download") %></b>
</p>

<% if current_user == @interpolation.user %>
<%= link_to 'Edit', edit_interpolation_path(@interpolation) %> |
<% end %>
<%= link_to 'Back', interpolations_path %>
<%= link_to 'Download', new_interpolation_download_path(@interpolation) %>
</div>