config/routes.rb
Interpolator::Application.routes.draw do
  

  match '/rate' => 'rater#create', :as => 'rate'

  resources :interpolations do
    member do
      post 'rate' 
    end
    resources :comments
    resources :downloads
  end

  resources :users

  resources :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'interpolations#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :crypted_password, :email, :password_salt, :persistence_token, :username, :password, :password_confirmation
  acts_as_authentic
  has_many :downloads
  has_many :comments
  has_many :ratings
  has_many :interpolations
  validates_presence_of :username

  ajaxful_rater
  letsrate_rater
  
  def options
    a = Array.new
    self.downloads.each do |d|
      d.interpolation.changes.each do |c|
        b = Array.new
        b.push(c.regex_old)
        b.push(c.regex_new)
        a.push(b)
      end
    end
    return a
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :check_auth, :only => [:edit, :update, :destroy]

  def check_auth

    if current_user != User.find(params[:id])
      flash[:notice] = "You can't edit this user."
      redirect_to users_path
    end
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        format.html { redirect_to(:interpolations, :notice => 'Registration successfull.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
 
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="login2">
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit "Sign up!", :id => 'submit' %>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %>
<h1 class="centerer">Editing user</h1>

<%= render 'form' %>

<p id="backlink"> <%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</p>

app/views/users/index.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %>
<h1 class="centerer">Listing users</h1>
<p id="notice"><%= notice %></p>
<div id="login2">
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <% if current_user == user %>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    <% else %>
    <td></td>
    <td></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>
<br />
 
<p id="backlink"><%= link_to 'New User', new_user_path %></p>

app/views/users/new.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %>
<h1 class="centerer">New user</h1>

<%= render 'form' %>

<p id='backlink'><%= link_to 'Back', users_path%></p>

app/views/users/show.html.erb
<%= link_to image_tag("logo_int.gif", :alt => "Interpolator"), :interpolations %><p id="notice"><%= notice %></p>
<h1 class="centerer">User Information</h1>
<div id="login2">
<div id="user_page">

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<b>Created:</b>
<% @user.interpolations.each do |i| %>
<p><%= link_to i.name, i %></p>
<% end %>

<b>Downloads:</b>
<% @user.downloads.each do |d| %>
<p>
  <%= link_to d.interpolation.name, d.interpolation %>
</p>
<% end %>

</div>
</div>
<p id="backlink">
<% if current_user == @user %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', interpolations_path %>
</p>